test: fix path to test fixtures
Currently, the test are failing with the following error:
$ rm -rf test/fixtures/simple-http/node_modules/
$ npm t

> @redhat/faas-js-runtime@0.0.2 test /work/faas-js-runtime
> nyc tape test/*.js | tap-spec

  Loads a user function with dependencies

internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module 'is-number'
Require stack:
/work/faas-js-runtime/test/fixtures/simple-http/index.js
/work/faas-js-runtime/test/test.js

This commit adds the fixture director so that the package.json files in
the fixtures are found.